### ISSUE TITLE
[ERROR] LXC Alpine Linux 3.15 - Not found

### ISSUE THREAD

**Issue by timonych** [Seb3thehacker/sphinx-server#10]
Hello, @Seb3thehacker !

Big Thanks for new version of Sphinx-server (previous linx-server), but I have a problem.
Download precompilled binary server for linux amd64, but it doesn't start.\

Only one message apears: **not found**.

```
linxserver:/opt/linx-server# linx-server-new
-ash: linx-server-new: not found
```

Can You please advice what can it be?

**Comment by Seb3thehacker** [comment]
What OS are you on? On linux you run ./linx-server

**Comment by Seb3thehacker** [comment]
So you downloaded the linux amd64 binary here: https://github.com/Seb3thehacker/sphinx-server/releases/download/v3.0.0/sphinx-server-v_linux-amd64 and you ran ./linx-server as root correct?

**Comment by timonych** [comment]
@Seb3thehacker 
Thanks for immediate feedback! :)

Correct

Binary has been run inside LXC Alpine Linux 3.15 under Proxmox 7.2 (Debian 11).\

By default all LXC contains only root user.

To be clear have done once again - no success :(

![image](https://user-images.githubusercontent.com/2186304/167799798-e1b5f5b9-cdbf-44e7-84f7-ab4936c4b27d.png)

**Comment by Seb3thehacker** [comment]
Ill look at this tomorrow in a VM and see whats going wrong. Though, on linux it usually requires a ./sphinx-server to run bianary files.

**Comment by timonych** [comment]
@Seb3thehacker 

Have remembered that sometimes workaround for Alpine Linux is install custom glibc. I think it will be useful in Docs for Alpine Linux users.

https://stackoverflow.com/a/38433396

Have installed glibc and now receive a more detailed error (Also such error on Windows I have received)
```
linxserver:/usr/local/bin# sphinx-server-v_linux-amd64 
2022/05/11 09:51:34 Error: could not load templatescould not locate box "templates"
```

**Comment by Seb3thehacker** [comment]
I'm guessing its just missing a dependency(s). I dont know what the solution is off the top of my head. It seems to only be an Alpine Linux issue. I assume you already looked up the error,  correct?

**Comment by timonych** [comment]
> I'm guessing its just missing a dependency(s). I dont know what the solution is off the top of my head. It seems to only be an Alpine Linux issue. I assume you already looked up the error, correct?

```
2022/05/11 09:51:34 Error: could not load templatescould not locate box "templates"
```
This error I have received on both OS: Alpine Linux 3.15 and Windows 11.

Should I open a new issue for this?

With initial start on Alpine Linux 3.15 need to install glibc - it's main dependency in sphinx-server (as I have understood)

**Comment by timonych** [comment]
Have tryed according to Dockerfile.
Manually download static and templates dir and put it to /go/src/github.com/andreimarcu/linx-server/*, but no sucess.

**Comment by Seb3thehacker** [comment]
Messed around with it today..... Not sure the issue yet.

**Comment by timonych** [comment]
To fix Alpine package need to use glibs from https://stackoverflow.com/a/38433396.

By the way, problem with templates do not accord to this issue.
